version: '3'

services:
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8001:8001"
  app_node:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app_node
    entrypoint: dockerize -wait tcp://db:3306 node index.js
    networks:
      - node-network
    volumes: 
      - ./node:/usr/src/app_node
    tty: true
    ports:
      - "9001:9001"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge